version: '3'
services:
  socket-app-1:
    build: .
    ports:
      - "8000:8000"
    networks:
      - app-network

    volumes:
      - ./server:/app

  socket-app-2:
    build: .
    ports:
      - "8001:8000"
    networks:
      - app-network
    
    volumes:
      - ./server:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
